version: '3.7'
services:
  app:
    build: .
    ports:
      - "2345:2345" #delve用のポート
      - "8080:8080" 
    volumes:
      - ./:/go/src
    working_dir: /go/src
    command: air -c .air.toml